// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Safari.Data.DbContext;

#nullable disable

namespace Safari.Data.Migrations
{
    [DbContext(typeof(SafariDbContext))]
    partial class SafariDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Safari.Data.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int>("MartyrId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(11)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("Id");

                    b.HasIndex("MartyrId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Safari.Data.Entities.Martyr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("Age")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("Bio")
                        .HasColumnType("VARCHAR(300)");

                    b.Property<string>("BirthDate")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("BurialPlace")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Education")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("FatherFirstName")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Job")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Marriage")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("MartyrDate")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("MartyrPlace")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("MissionName")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("PhotoFileUrl")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<string>("TestamentFileUrl")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<string>("TestamentText")
                        .HasColumnType("VARCHAR(500)");

                    b.HasKey("Id");

                    b.ToTable("Martyrs");
                });

            modelBuilder.Entity("Safari.Data.Entities.Comment", b =>
                {
                    b.HasOne("Safari.Data.Entities.Martyr", "Martyr")
                        .WithMany("Comments")
                        .HasForeignKey("MartyrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Comment_Martyr");

                    b.Navigation("Martyr");
                });

            modelBuilder.Entity("Safari.Data.Entities.Martyr", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
